# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/code
      - ./credentials:/code/credentials # Mount credentials directory
    ports:
      - "5052:5052"
    environment:
      - DATABASE_URI=postgresql://neondb_owner:Od9UnVJ2Wvfr@ep-square-star-a8fg370g-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - MAIL_SERVER=smtp.hashforgamers.co.in
      - MAIL_PORT=587
      - MAIL_USERNAME=support@hashforgamers.co.in
      - MAIL_PASSWORD=h3b:@yasDm
      - MAIL_DEFAULT_SENDER=support@hashforgamers.co.in
      - SECRET_KEY=your_secret_key
      - GOOGLE_DRIVE_FOLDER_ID=16muxbG0nfp6PEjdJ-u1lwrZASpoW82b3
      - GOOGLE_APPLICATION_CREDENTIALS=/code/credentials/google_service_account.json # Updated path
      - DEBUG_MODE=true

      # *** NEW: Replace these with your actual Cloudinary credentials ***
      - CLOUDINARY_CLOUD_NAME=dxjjigepf
      - CLOUDINARY_API_KEY=181315914336585
      - CLOUDINARY_API_SECRET=SECRET_KEY

  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: vendor_db
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:

#*** postgresql://neondb_owner:Od9UnVJ2Wvfr@ep-patient-sound-a8cq577j-pooler.eastus2.azure.neon.tech/neondb?sslmode=require

# develop-2 branch db url
#postgresql://neondb_owner:npg_tF14oULHzflV@ep-divine-bird-a8m81vvk-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
